name: Send Lunch Menu

on:
  schedule:
    - cron: '0 12 * * 1-5'
      timezone: "Asia/Seoul"
  workflow_dispatch:

jobs:
  send-menu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - run: pip install -r requirements.txt

      - run: python main.py
        env:
          PDF_NAME_TEMPLATE: ${{ vars.PDF_NAME_TEMPLATE }}
          WEB_URL_PREFIX: ${{ vars.WEB_URL_PREFIX }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
