name: Send Lunch Menu

on:
  schedule:
    - cron: '0 12 * * 1-5'
      timezone: "Asia/Seoul"
  workflow_dispatch:

jobs:
  send-menu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - run: pip install -r requirements.txt

      - run: python main.py
        env:
          PDF_TEMPLATE: ${{ secrets.PDF_TEMPLATE }}
          WEB_URL: ${{ secrets.WEB_URL }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
